name = "Anatoly"
author = "Timberwolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "806f168edd8cb0005b6989edd62c89263ce388450d3414cc0c2c5cdb00e99732"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
