name = "Anatoly"
author = "Timberwolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b6064e7fb3671d27d56c53c795615383b7098ddfdbb1fe31baf2b21e3e71186"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
