name = "Anatoly"
author = "Timberwolf"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96ef0282e6e0c5a81d2667d329c326cd99620f56743851f9f1540acdd141566f"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
